### ISSUE TITLE
催更

### ISSUE THREAD

**Issue by vmlankub** [LMOliver/lmoliver.github.io#17]
什么时候更新啊。。。

记得更新以后@一下大号
@MinecraftFuns

**Comment by vmlankub** [comment]
或者线下物理联系

**Comment by LMOliver** [comment]
@MinecraftFuns

膜拜 Siyuan 0.6.4 更新了！

查看 [LMOliver/mosiyuan](https://github.com/LMOliver/mosiyuan) 和 [LMOliver/lmoliver.github.io/mosiyuan/index.html](https://github.com/LMOliver/lmoliver.github.io/blob/master/mosiyuan/index.html) 了解本次更新的技术性内容。

（只需要搬运 [LMOliver/lmoliver.github.io/mosiyuan](https://github.com/LMOliver/lmoliver.github.io/tree/master/mosiyuan) 内的东西即可。）
