### ISSUE TITLE
找到一个可以的方案

### ISSUE THREAD

**Issue by vmlankub** [LMOliver/lmoliver.github.io#18]
@LMOliver 先注册一个（公用的）机器人账号
然后根据 https://segmentfault.com/a/1190000015144126 这篇文章

可以先给账号生成一个 token **记得这个token不能明文放在项目里，不然会被github自动和谐**

**Comment by vmlankub** [comment]
创建一个项目，考虑到修改文件极其复杂，这里不妨使用issues

**Comment by vmlankub** [comment]
设你写了一个加密编码的函数 ``string encode(string origin, string password)``

**Comment by vmlankub** [comment]
给每个用户创建一条 issue ，命名是用户名，里面的每条内容用``encode()``和密码加密，就能实现一个简单的存储功能

**Comment by vmlankub** [comment]
当然还有很多细节需要研究，但这可能是一个比较可行且实用的方法（前提是没有哪个用户滥用你的token删除别人的存档）

**Comment by vmlankub** [comment]
以下是一些细节：
* 既然``token``不能明文保存在项目里，在项目中保存``encode(token, default_password)``，前端decode
* 使用api查看issue是否存在来判定用户名能否注册（其实这步有个大漏洞，但是我们做简单的项目就暂时容忍一下吧，**前端永远不可信任**）
* （建议）issue的第一条是``encode("hello, world", password)``的结果，方便验证用户的密码正确性

本人菜鸡，如有错误，请谅解

**Comment by LMOliver** [comment]
有点不靠谱……

曾经 [demos/network](https://lmoliver.github.io/demos/network/index.html) 的存档是用简单字符替换编码的，被普通玩家复读字符（`abcdefgbhijjk` => `{"money":100}`，那么`abcdefgbhijjjjjjjjjjk` 就是 `{"money":10000000000}`！）爆踩，GG。

不要小看别人的乱搞能力 QAQ
